name: Test

on:
  push:
    branches: [main]
  pull_request:

env:
  ZIG_VERSION: 0.16.0

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            dbus \
            gnome-keyring

      - name: Run tests on Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          dbus-run-session -- bash -lc '
            eval "$(printf "\n" | gnome-keyring-daemon --unlock --components=secrets)"
            zig build --verbose --summary all test
            zig build --verbose --summary all test -Dfile-backend=true
          '

      - name: Run tests
        if: runner.os != 'Linux'
        run: |
          zig build --verbose --summary all test
          zig build --verbose --summary all test -Dfile-backend=true
